AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This CloudFormation template creates the following resources for a sample application:
    3) IAM group with the managed policy AWSLambda_FullAccess attached.
    4) IAM user as a member of the group to be used as a service account.
    5) IAM access key for the service account

  Be sure to protect the credentials that are created and
  delete this stack when you are finished with the course.

Resources:
  LambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: "/"
      Description: "Policy to manage the Lambda functions for the sample application."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "lambda:InvokeFunction"
              - "lambda:UpdateFunctionCode"
              - "lambda:GetFunctionConfiguration"
              - "lambda:UpdateFunctionConfiguration"
            Resource:
              - "*"
            Effect: "Allow"

  ServiceAccount:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${AWS::StackName}-Service-Account
      ManagedPolicyArns:
        - !Ref LambdaPolicy

  Keys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref ServiceAccount

Outputs:
  AwsAccessKeyId:
    Description: The AWS_ACCESS_KEY_ID for the service account. Please keep this value secure.
    Value:
      !Ref Keys

  AwsSecretAccessKey:
    Description: The AWS_SECRET_ACCESS_KEY for the service account. Please keep this value secure.
    Value:
      !GetAtt Keys.SecretAccessKey

  AwsDefaultRegion:
    Description: The AWS_DEFAULT_REGION where the stack is deployed.
    Value:
      !Sub ${AWS::Region}
