image: atlassian/default-image:4

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y rustc
          - rustc -V
    - step:
        script:
          - apt-get update
          - apt-get install -y rustc
          - rustc -V
