image: atlassian/default-image:4

definitions:
  steps:
    - step: &deploy
        name: Deploy the Application
        script:
          - echo "Environment - $BITBUCKET_DEPLOYMENT_ENVIRONMENT"
          - echo "Domain      - $DOMAIN"

pipelines:
  default:
    - step:
        <<: *deploy
        deployment: Staging
        name: 'Deployment to Staging'
    - step:
        <<: *deploy
        name: 'Deployment to Production'
        deployment: production

