image: 'atlassian/default-image:3'

definitions:
  steps:
    - step: &build_and_test
        name: Build and Test
        script:
          - echo "Your build and test goes here..."
    
    - step: &lint
        name: Lint
        script:
          - echo "Your linting goes here..."
    
    - step: &security_scan
        name: Security scan
        script:
          - echo "Your security scan goes here..."
    
    - step: &set_up_staging
        name: Set up Staging
        script:
          - echo "set up staging deployment"
    
    - step: &deployment_to_staging
        name: Deployment to Staging
        deployment: staging
        script:
          - echo "Your deployment to staging script goes here..."
        after-script:
          - echo "Clean up the deployment if anything fails..."
    
    - step: &set_up_production
        name: Set up Production
        script:
          - echo "set up production deployment"
    
    - step: &deployment_to_production
        name: Deployment to Production
        deployment: production
        script:
          - echo "Your deployment to production script goes here..."
        after-script:
          - echo "Clean up the deployment if anything fails..."

pipelines:
  default:
    - parallel:
        - *build_and_test
        - *lint
        - *security_scan

  branches:
    feature/*:
      - parallel:
          - *build_and_test
          - *lint
          - *security_scan
      - stage:
          name: Staging
          steps:
            - *set_up_staging
            - *deployment_to_staging
    main:
      - parallel:
          - *build_and_test
          - *lint
          - *security_scan
      - stage:
          name: Staging
          steps:
            - *set_up_staging
            - *deployment_to_staging
      - stage:
          name: Production
          trigger: manual
          steps:
            - *set_up_production
            - *deployment_to_production

  pull-requests:
    '**':
      - parallel:
          - *build_and_test
          - *lint
          - *security_scan
      - stage:
          name: Pull Request
          steps:
            - step:
                name: Set up pull request tasks
                script:
                  - echo "PR task 1"
                  - echo "PR task 2"
            - step:
                name: Complete pull request tasks
                script:
                  - echo "PR task 3"
                  - echo "PR task 4"
      - stage:
          name: Staging
          steps:
            - *set_up_staging
            - *deployment_to_staging
