image: atlassian/default-image:4

definitions:
  services:
    database:
      image: postgres:14.3
      environment:
        POSTGRES_DB: 'db'
        POSTGRES_USER: 'db'
        POSTGRES_PASSWORD: 'testingtesting123'

pipelines:
  default:
    - step:
        image: python:3
        services:
          - database
        name: Test Python
        script:
          - echo "Your Python tests go here"
          - pip install psycopg2-binary
          - python3 -m unittest --verbose app_test.py 
    - step:
        image: ruby:3
        services:
          - database
        name: Test Ruby
        script:
          - echo "Your Ruby tests go here"
          - bundle install
          - bundle exec ruby app_test.rb

